# Generated by Django 5.1 on 2024-09-01 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_alter_drinkfavorite_profile'),
        ('profiles', '0002_alter_follow_follower_alter_follow_following'),
        ('reviews', '0003_alter_comment_profile_alter_commentlike_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drink', to='drinks.drink'),
        ),
        migrations.AlterField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.profile'),
        ),
    ]
